### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by thefooly** [LuCEresearchlab/scratch-chrome-plugin#12]
Plugin:
- [ ]  Implement UI for features:
   - [ ] check 
   - [ ] evaluate (make sure that changes are clear)
   - [ ] step-by-step
   - [ ] list of expression
- [ ] multiple locales (IT / EN)
- [ ] better UI for popup app
- [ ] publish on chrome store

-----

Demo:
- [ ] create activities for students
- [ ] alpha: in-class activities 8-9-10 August
- [ ] final activities ready for September
